<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Services\DataPruningService;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use InvalidArgumentException;
use Spatie\Activitylog\Models\Activity;
use Tests\TestCase;

class DataPruningTest extends TestCase
{
    use RefreshDatabase;

    private DataPruningService $service;

    protected function setUp(): void
    {
        parent::setUp();

        $this->service = app(DataPruningService::class);
    }

    public function test_global_disabled_toggle_halts_pruning_operations(): void
    {
        config(['pruning.enabled' => false]);

        $report = $this->service->pruneAll();

        $this->assertFalse($report['enabled']);
        $this->assertSame('disabled', $report['status']);
        $this->assertSame(0, $report['total_pruned']);
        $this->assertEmpty($report['tables']);
    }

    public function test_dry_run_calculates_targeted_records_without_deleting_them(): void
    {
        // Insert records older than 90 days
        $oldDate = Carbon::now()->subDays(100);
        for ($i = 1; $i <= 3; $i++) {
            DB::table('activity_log')->insert([
                'description' => "Old activity {$i}",
                'created_at' => $oldDate,
                'updated_at' => $oldDate,
            ]);
        }

        $result = $this->service->pruneTable('activity_log', dryRun: true);

        $this->assertTrue($result['dry_run']);
        $this->assertSame(3, $result['date_pruned']);
        $this->assertSame(3, $result['total_pruned']);
        // Crucial: records must still exist in DB
        $this->assertSame(3, DB::table('activity_log')->count());
    }

    public function test_date_based_pruning_deletes_records_older_than_retention_period(): void
    {
        $oldDate = Carbon::now()->subDays(95);
        $freshDate = Carbon::now()->subDays(10);

        // 2 expired records
        DB::table('activity_log')->insert([
            'description' => 'Expired activity 1',
            'created_at' => $oldDate,
            'updated_at' => $oldDate,
        ]);
        DB::table('activity_log')->insert([
            'description' => 'Expired activity 2',
            'created_at' => $oldDate,
            'updated_at' => $oldDate,
        ]);

        // 1 fresh record
        DB::table('activity_log')->insert([
            'description' => 'Active fresh activity',
            'created_at' => $freshDate,
            'updated_at' => $freshDate,
        ]);

        $this->assertSame(3, DB::table('activity_log')->count());

        $result = $this->service->pruneTable('activity_log', dryRun: false);

        $this->assertSame(2, $result['date_pruned']);
        $this->assertSame(2, $result['total_pruned']);

        // The 2 expired activities are gone
        $this->assertDatabaseMissing('activity_log', ['description' => 'Expired activity 1']);
        $this->assertDatabaseMissing('activity_log', ['description' => 'Expired activity 2']);

        // The active fresh activity remains
        $this->assertDatabaseHas('activity_log', ['description' => 'Active fresh activity']);

        // An audit trail record is generated by the pruning service
        $this->assertDatabaseHas('activity_log', ['log_name' => 'data_pruning']);
    }

    public function test_count_based_pruning_deletes_excess_oldest_records(): void
    {
        config(['pruning.tables.failed_jobs.max_records' => 3]);
        config(['pruning.tables.failed_jobs.retention_days' => 365]); // High retention so date doesn't prune

        $baseDate = Carbon::now()->subDays(10);

        // Insert 5 failed jobs with distinct timestamps
        for ($i = 1; $i <= 5; $i++) {
            DB::table('failed_jobs')->insert([
                'uuid' => (string) Str::uuid(),
                'connection' => 'database',
                'queue' => "queue_{$i}",
                'payload' => '{}',
                'exception' => "Exception {$i}",
                'failed_at' => (clone $baseDate)->addHours($i),
            ]);
        }

        $this->assertSame(5, DB::table('failed_jobs')->count());

        $result = $this->service->pruneTable('failed_jobs', dryRun: false);

        // Excess is 5 - 3 = 2
        $this->assertSame(2, $result['count_pruned']);
        $this->assertSame(2, $result['total_pruned']);
        $this->assertSame(3, DB::table('failed_jobs')->count());

        // Oldest 2 (queue_1 & queue_2) should be pruned; queue_3, 4, 5 must remain
        $remainingQueues = DB::table('failed_jobs')->pluck('queue')->all();
        $this->assertNotContains('queue_1', $remainingQueues);
        $this->assertNotContains('queue_2', $remainingQueues);
        $this->assertContains('queue_3', $remainingQueues);
        $this->assertContains('queue_4', $remainingQueues);
        $this->assertContains('queue_5', $remainingQueues);
    }

    public function test_sovereign_table_exclusion_safeguard_throws_exception_on_critical_tables(): void
    {
        $sovereignTables = ['users', 'roles', 'permissions', 'sessions', 'cache', 'jobs'];

        foreach ($sovereignTables as $table) {
            $this->assertTrue($this->service->isTableProtected($table), "Table {$table} must be detected as protected.");

            // Attempting to prune a protected table must throw InvalidArgumentException
            config(["pruning.tables.{$table}" => [
                'table' => $table,
                'retention_days' => 30,
            ]]);

            $this->expectException(InvalidArgumentException::class);
            $this->service->pruneTable($table);
        }
    }

    public function test_pruning_records_activity_log_entry_upon_deletion(): void
    {
        $oldDate = Carbon::now()->subDays(40);

        // Insert old failed job
        DB::table('failed_jobs')->insert([
            'uuid' => (string) Str::uuid(),
            'connection' => 'database',
            'queue' => 'default',
            'payload' => '{}',
            'exception' => 'TestException',
            'failed_at' => $oldDate,
        ]);

        $this->service->pruneTable('failed_jobs', dryRun: false);

        $activity = Activity::where('log_name', 'data_pruning')->latest('id')->first();
        $this->assertNotNull($activity);
        $this->assertSame('failed_jobs', $activity->properties['table'] ?? null);
        $this->assertSame(1, $activity->properties['total_pruned'] ?? null);
    }

    public function test_notifications_only_read_filter_prunes_only_read_notifications_when_configured(): void
    {
        config(['pruning.tables.notifications.retention_days' => 30]);
        config(['pruning.tables.notifications.only_read' => true]);

        $oldDate = Carbon::now()->subDays(45);

        // 1 old READ notification
        DB::table('notifications')->insert([
            'id' => (string) Str::uuid(),
            'type' => 'App\\Notifications\\TestAlert',
            'notifiable_type' => 'App\\Models\\User',
            'notifiable_id' => 1,
            'data' => json_encode(['title' => 'Read Notice']),
            'read_at' => $oldDate,
            'created_at' => $oldDate,
            'updated_at' => $oldDate,
        ]);

        // 1 old UNREAD notification (read_at is null)
        DB::table('notifications')->insert([
            'id' => (string) Str::uuid(),
            'type' => 'App\\Notifications\\TestAlert',
            'notifiable_type' => 'App\\Models\\User',
            'notifiable_id' => 1,
            'data' => json_encode(['title' => 'Unread Notice']),
            'read_at' => null,
            'created_at' => $oldDate,
            'updated_at' => $oldDate,
        ]);

        $result = $this->service->pruneTable('notifications', dryRun: false);

        // Only the read notification should be pruned
        $this->assertSame(1, $result['date_pruned']);
        $this->assertSame(1, DB::table('notifications')->count());
        $this->assertNull(DB::table('notifications')->first()?->read_at);
    }

    public function test_artisan_data_prune_command_runs_dry_run_and_table_scoped(): void
    {
        $this->artisan('data:prune', ['--dry-run' => true])
            ->expectsOutputToContain('[DRY-RUN MODE]')
            ->assertExitCode(0);

        $this->artisan('data:prune', ['--table' => 'activity_log', '--dry-run' => true])
            ->expectsOutputToContain('Pruning specific table: [activity_log]')
            ->assertExitCode(0);
    }

    public function test_artisan_data_prune_command_fails_gracefully_on_unconfigured_table(): void
    {
        $this->artisan('data:prune', ['--table' => 'non_existent_table'])
            ->expectsOutputToContain('Data pruning failed')
            ->assertExitCode(1);
    }
}
